
name: shell

on:
  workflow_dispatch:
    inputs:
      arch:
        description: Architecture
        required: true
        type: choice
        options:
        - x86_64
        - aarch64
        default: x86_64
      release:
        description: 'OpenBSD release'
        required: true
        type: choice
        options:
        - '7.6'
        - '7.5'
        - '7.4'
        - '7.3'
        - '7.2'
        default: '7.6'

jobs:
  runshell:
    runs-on: ubuntu-latest
    name: Start a openbsd shell
    steps:
    - name: Starting a openbsd VM, please wait. It may take 3 minutes
      uses: vmactions/openbsd-vm@v1
      with:
        arch: ${{ github.event.inputs.arch || 'x86_64' }}
        release: ${{ github.event.inputs.release || '7.6' }}
        nat: |
          "8000": "80"
        envs: 'TestingDomain TEST_PREFERRED_CHAIN TEST_ACME_Server INPUT_*'
        sync: sshfs
        run: |
          pwd
          ls -lah
          whoami
          env
          uname -a
    - uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
